// Aiden Tsang
// Lab #0

#include <iostream>
using namespace std;

int main()
{
    int num1, num2, sum;

    cout << "\nMy name is Aiden Tsang" << endl;

    cout << "\nEnter the first number: ";
    cin >> num1;

    cout << "\nEnter the second number: ";
    cin >> num2;


    sum = num1 + num2;
    cout << "\nThe sum of " << num1 << " and " << num2 << " is " << sum << endl;

}

/*
  Launching: '/Users/aidentsang/Pierce college Labs C++/CS216_L0_AT/main'
Working directory: '/Users/aidentsang/Pierce college Labs C++/CS216_L0_AT'
1 arguments:
argv[0] = '/Users/aidentsang/Pierce college Labs C++/CS216_L0_AT/main'

My name is Aiden Tsang

Enter the first number: 5    

Enter the second number: 6

The sum of 5 and 6 is 11
Process exited with status 0

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

*/
